export const PERMISSIONS = {
  // User Management
  USER_VIEW: 'user.view',
  USER_MANAGE: 'user.manage',

  // Company & Business Development
  COMPANY_VIEW: 'company.view',
  COMPANY_MANAGE: 'company.manage',

  // Job Requirements
  JOB_VIEW: 'job.view',
  JOB_MANAGE: 'job.manage',

  // Candidate Master
  CANDIDATE_VIEW_ALL: 'candidate.view_all',
  CANDIDATE_VIEW_ASSIGNED: 'candidate.view_assigned',
  CANDIDATE_MANAGE: 'candidate.manage',
  CANDIDATE_IMPORT: 'candidate.import',
  CANDIDATE_MERGE: 'candidate.merge',

  // Application & Lead Assignment
  APPLICATION_VIEW_ALL: 'application.view_all',
  APPLICATION_VIEW_OWN: 'application.view_own',
  APPLICATION_ASSIGN: 'application.assign',
  APPLICATION_MANAGE: 'application.manage',

  // Calling & Callbacks
  CALLING_LOG: 'calling.log',
  CALLBACK_MANAGE_ALL: 'callback.manage_all',
  CALLBACK_MANAGE_OWN: 'callback.manage_own',

  // Screening & Shortlisting
  SCREENING_VIEW: 'screening.view',
  SCREENING_EVALUATE: 'screening.evaluate',
  SHORTLIST_FINALIZE: 'shortlist.finalize',

  // Client Submission & Interviews
  SUBMISSION_MANAGE: 'submission.manage',
  INTERVIEW_MANAGE: 'interview.manage',
  SELECTION_MANAGE: 'selection.manage',
  JOINING_MANAGE: 'joining.manage',

  // Operations & Quality
  QUALITY_REVIEW: 'quality.review',
  REPORTS_OPERATIONS: 'reports.operations',
  REPORTS_RECRUITMENT: 'reports.recruitment',
  AUDIT_VIEW: 'audit.view',
  SETTINGS_MANAGE: 'settings.manage',
} as const;

export type PermissionKey = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

export const SYSTEM_ROLES = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  OPERATIONS_HEAD: 'OPERATIONS_HEAD',
  SCREENING_MANAGER: 'SCREENING_MANAGER',
  EXECUTIVE: 'EXECUTIVE',
  TEAM_LEAD: 'TEAM_LEAD',
  BUSINESS_DEVELOPMENT_MANAGER: 'BUSINESS_DEVELOPMENT_MANAGER',
  BUSINESS_DEVELOPMENT_EXECUTIVE: 'BUSINESS_DEVELOPMENT_EXECUTIVE',
  FINANCE_MANAGER: 'FINANCE_MANAGER',
} as const;

export type SystemRoleKey = (typeof SYSTEM_ROLES)[keyof typeof SYSTEM_ROLES];

// Default Role-to-Permissions Matrix
export const DEFAULT_ROLE_PERMISSIONS: Record<SystemRoleKey, string[]> = {
  SUPER_ADMIN: Object.values(PERMISSIONS),
  OPERATIONS_HEAD: [
    PERMISSIONS.USER_VIEW,
    PERMISSIONS.COMPANY_VIEW,
    PERMISSIONS.COMPANY_MANAGE,
    PERMISSIONS.JOB_VIEW,
    PERMISSIONS.JOB_MANAGE,
    PERMISSIONS.CANDIDATE_VIEW_ALL,
    PERMISSIONS.CANDIDATE_VIEW_ASSIGNED,
    PERMISSIONS.CANDIDATE_MANAGE,
    PERMISSIONS.CANDIDATE_IMPORT,
    PERMISSIONS.CANDIDATE_MERGE,
    PERMISSIONS.APPLICATION_VIEW_ALL,
    PERMISSIONS.APPLICATION_VIEW_OWN,
    PERMISSIONS.APPLICATION_ASSIGN,
    PERMISSIONS.APPLICATION_MANAGE,
    PERMISSIONS.CALLING_LOG,
    PERMISSIONS.CALLBACK_MANAGE_ALL,
    PERMISSIONS.SCREENING_VIEW,
    PERMISSIONS.SCREENING_EVALUATE,
    PERMISSIONS.SHORTLIST_FINALIZE,
    PERMISSIONS.SUBMISSION_MANAGE,
    PERMISSIONS.INTERVIEW_MANAGE,
    PERMISSIONS.SELECTION_MANAGE,
    PERMISSIONS.JOINING_MANAGE,
    PERMISSIONS.QUALITY_REVIEW,
    PERMISSIONS.REPORTS_OPERATIONS,
    PERMISSIONS.REPORTS_RECRUITMENT,
    PERMISSIONS.AUDIT_VIEW,
  ],
  SCREENING_MANAGER: [
    PERMISSIONS.JOB_VIEW,
    PERMISSIONS.JOB_MANAGE,
    PERMISSIONS.COMPANY_VIEW,
    PERMISSIONS.CANDIDATE_VIEW_ALL,
    PERMISSIONS.CANDIDATE_VIEW_ASSIGNED,
    PERMISSIONS.APPLICATION_VIEW_ALL,
    PERMISSIONS.APPLICATION_VIEW_OWN,
    PERMISSIONS.SCREENING_VIEW,
    PERMISSIONS.SCREENING_EVALUATE,
    PERMISSIONS.SHORTLIST_FINALIZE,
    PERMISSIONS.SUBMISSION_MANAGE,
    PERMISSIONS.INTERVIEW_MANAGE,
    PERMISSIONS.SELECTION_MANAGE,
    PERMISSIONS.JOINING_MANAGE,
    PERMISSIONS.REPORTS_RECRUITMENT,
  ],
  EXECUTIVE: [
    PERMISSIONS.CANDIDATE_VIEW_ASSIGNED,
    PERMISSIONS.APPLICATION_VIEW_OWN,
    PERMISSIONS.CALLING_LOG,
    PERMISSIONS.CALLBACK_MANAGE_OWN,
  ],
  TEAM_LEAD: [
    PERMISSIONS.CANDIDATE_VIEW_ALL,
    PERMISSIONS.CANDIDATE_VIEW_ASSIGNED,
    PERMISSIONS.APPLICATION_VIEW_ALL,
    PERMISSIONS.APPLICATION_VIEW_OWN,
    PERMISSIONS.CALLING_LOG,
    PERMISSIONS.CALLBACK_MANAGE_ALL,
    PERMISSIONS.REPORTS_OPERATIONS,
  ],
  BUSINESS_DEVELOPMENT_MANAGER: [
    PERMISSIONS.COMPANY_VIEW,
    PERMISSIONS.COMPANY_MANAGE,
    PERMISSIONS.JOB_VIEW,
    PERMISSIONS.JOB_MANAGE,
  ],
  BUSINESS_DEVELOPMENT_EXECUTIVE: [
    PERMISSIONS.COMPANY_VIEW,
    PERMISSIONS.JOB_VIEW,
  ],
  FINANCE_MANAGER: [
    PERMISSIONS.COMPANY_VIEW,
    PERMISSIONS.REPORTS_OPERATIONS,
  ],
};
